### ISSUE TITLE
The translator is not working

### ISSUE THREAD

**Issue by alvapatrice** [oguzhaninan/Buka#16]
How to configure the translator? Mine is prompting an error in the console that says
"Returned unrecognised Json Format, maybe the api has changed"

**Comment by oguzhaninan** [comment]
Hi,
There's no problem with the Internet, is there? I tried and it's working right now.

**Comment by alvapatrice** [comment]
I'm in china where google is brocked but I use a vpn and my computer can access all the blocked sites. Can that be a reason? Maybe that buka is not connecting to the internet via my VPN?

P Nostalgie
Chengdu Neusoft University
________________________________

**Comment by oguzhaninan** [comment]
VPN can cause problems. Have you turned off the VPN and tried it?

**Comment by alvapatrice** [comment]
Yeah tried it , but the problem still is the same. Are there any other configurations required to make the translator work ?

P Nostalgie
Chengdu Neusoft University
________________________________

**Comment by oguzhaninan** [comment]
There is no configuration. When did you install Buka?

**Comment by alvapatrice** [comment]
Last week, on Tuesday 12th September 2017. I installed from the source codes

P Nostalgie
Chengdu Neusoft University
________________________________

**Comment by oguzhaninan** [comment]
You try do it by install one of [these packages](https://github.com/oguzhaninan/Buka/releases).

**Comment by alvapatrice** [comment]
during the installation i get this error
![installation](https://user-images.githubusercontent.com/19281283/30693721-6b5d1d70-9f03-11e7-8a2d-2d1d34341e18.png)

and when i run electron . i get the following error in my console
![image-error](https://user-images.githubusercontent.com/19281283/30693745-852fa6e6-9f03-11e7-8ab4-1df910b43d48.png)

is it the problem with my computer? I have failed to figure out what is going on

**Comment by oguzhaninan** [comment]
There may be a problem with Windows. It works fine on Linux.
