### ISSUE TITLE
Suggest License

### ISSUE THREAD

**Issue by VoLuong** [oguzhaninan/Buka#3]
MIT license ? Maybe ?

**Comment by mtuchi** [comment]
Hello,
I recent just forked this project, i need to know what type of license 
are you guys planning to use ?

**Comment by LewisVo** [comment]
@mtuchi He is using MIT. https://github.com/oguzhaninan/Buka/blob/master/LICENSE

**Comment by mtuchi** [comment]
Thanks @LewisVo
