### ISSUE TITLE
Not occupying full space in i3wm

### ISSUE THREAD

**Issue by sohnryang** [oguzhaninan/Buka#35]
In i3wm, buka does not occupy full space.

**Comment by h3ct0rjs** [comment]
I've checked this @sohnryang but when you go from toggle tiling or  floating the window and then you go back to normal mod  it will solve the problem :smile: , it seems like this is a problem of the window manager not for the ebook manager.

**Comment by sohnryang** [comment]
Oh I see.

**Comment by sohnryang** [comment]
Closing the issue since it's not Buka's bug.
