### ISSUE TITLE
Buka doesn't load on Ubuntu 18.04

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [oguzhaninan/Buka#40]
When trying to open the application via command line I get the following error
```
No schema files found: doing nothing.
[1]    9604 illegal hardware instruction (core dumped)  buka
```
Note: I installed using `snap`

**Comment by iusmac** [comment]
> When trying to open the application via command line I get the following error
> 
> ```
> No schema files found: doing nothing.
> [1]    9604 illegal hardware instruction (core dumped)  buka
> ```
Same problem. At the moment I solve it by installing the .deb package from releases.

**Comment by hackel** [comment]
Same on 19.10, but I don't get the schema error, just illegal hardware instruction.  It makes me very curious what it is trying to do, but I'm not motivated enough to figure out how to debug a snap app.  I do appreciated having a confined snap app, but not much use if it doesn't work!

**Comment by zeroidentidad** [comment]
**funciona bien, lo instalé con el archivo deb** (_Buka_1.0.0_amd64.deb_)
![captura](https://user-images.githubusercontent.com/2924638/66798746-9ca44700-eed4-11e9-88f7-09c6f7efb256.png)

**Comment by Vlad-Ozik** [comment]
I have Ubuntu 18.04.4 LTS GMONE 3.28.2:
1. Download and install Buka deb
`sudo dpkg --install Buka_1.0.0_amd64.deb`
2. install gconf-service
`sudo apt install gconf-service`
3. Fix dependenciens
`sudo apt --fix-broken install`

It works for me

**Comment by alexandrebarbaruiva** [comment]
Works for me too

**Comment by mcrisc** [comment]
Not working for me.

```
$ Buka 
(Buka:45016): Pango-ERROR **: 14:45:44.437: Harfbuzz version too old (1.3.1)
Trace/breakpoint trap (core dumped)
```

System:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
