### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by julianorafael** [oguzhaninan/Buka#5]
I've been wanting to develop an application like this for so long but couldn't wrap my head around what exactly that I wanted. There's a few features that I thing would improve this application so much.

1. Be able to rename the files and change it's title and author properties and have them changed on actual filename too.
2. Tags. I want to add tags to the books about the subject and its content. Then I want to be able to quickly search through them.
3. List view with Title, Author and Tags.
4. A debounce on the search input. Seriously, it is annoying the flashing you get every time you add a letter to the search field.

**Comment by oguzhaninan** [comment]
Thank you for your suggestions. It will be in the next release.

**Comment by julianorafael** [comment]
Awesome. I can help you out with the development if you wish.

**Comment by oguzhaninan** [comment]
It would be great.
