### ISSUE TITLE
\how to install on macOs

### ISSUE THREAD

**Issue by agustif** [oguzhaninan/Buka#9]

**Comment by handleman** [comment]
You can build mac build (application) manually pretty easy. 
1. Download or `git clone` this repository to your Mac.  
2. Open yours Mac terminal application
3. Go to the folder where you have downloaded\cloned repo. For example `cd ~/Downloads/Buka`
4.  Run `npm install && npm run package-mac-x64`, and after it you should find new folder `bundle` created during the build.
5. inside `bundle` folder you would be able to find `.app` file which you can copy to your "Applications" folder, and then just start the application from there.
